### ISSUE TITLE
with MST

### ISSUE THREAD

**Issue by paxarpp** [Eureka-Shoulders/fetchx#10]
is it possible, replace from mobx to mobx-state-tree?

**Comment by devzgabriel** [comment]
Thanks for your contribution, we will review this option and return what is decided in a future comment on this issue.

**Comment by paxarpp** [comment]
ok

**Comment by SampaioLeal** [comment]
Can you write some details about this change? I don't like MST for my reasons... And I think this could be more "limited"
Let's talk 😊

**Comment by paxarpp** [comment]
I agree, the case is specific, but it may not be very difficult, while the project is at the beginning of the journey, try to make adapters for variations of the state managers, and since I use mst for work, I suggested it.
